use_frameworks!

platform :ios, '11.0'

target 'ReactNativeInspector_Example' do
  pod 'ReactNativeInspector', :path => '../'

  target 'ReactNativeInspector_Tests' do
    inherit! :search_paths

    
  end
end
